### ISSUE TITLE
Strange parameter at blocked callback call

### ISSUE THREAD

**Issue by dionys** [chiselwright/plack-middleware-xsrfblock#19]
[Line 159](https://github.com/chiselwright/plack-middleware-xsrfblock/blob/4864ff5259c387f43510f99240ae4f353efc1563/lib/Plack/Middleware/XSRFBlock.pm#L509):

    return $app_for_blocked->($env, $@, app => $self->app);

Value of `$@` variable not defined here. Maybe you mean `$msg`?

**Comment by dakkar** [comment]
agree, passing the last exception is not useful, please pass the `$msg` (and document those arguments)

**Comment by chiselwright** [comment]
Due to be merged and released with #21

**Comment by chiselwright** [comment]
https://metacpan.org/release/CHISEL/Plack-Middleware-XSRFBlock-0.0.13
